<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="P_GantryDiffSup" Id="{954b9861-204f-4ae9-b8f5-f376391fb77a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_GantryDiffSup
VAR
	fbXGantryMonitor	:	FB_GantryDifferenceMonitor;
	fbYGantryMonitor	:	FB_GantryDifferenceMonitor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

fbXGantryMonitor(Gantry:=XGantry);
fbYGantryMonitor(Gantry:=YGantry);]]></ST>
    </Implementation>
    <LineIds Name="P_GantryDiffSup">
      <LineId Id="9" Count="1" />
      <LineId Id="8" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>