<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="P_MotionSup" Id="{a34595bb-b6ff-449d-b539-c9e2760a9a1c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_MotionSup
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_MotionSup">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>